### ISSUE TITLE
Tomei Vacina!!!

### ISSUE THREAD

**Issue by RochaCarla** [fga-eps-mds/Qualifying-Software-Engineers-Undergraduates-in-DevOps#10]
Dia emocionante da nossa vacinação!
deixe aqui o registro desse momento maravilhoso !

**Comment by RochaCarla** [comment]
![image](https://user-images.githubusercontent.com/5897389/129188972-e8afd9e9-b6db-4bb5-bca1-147abae5e982.png)

**Comment by Thais-ra** [comment]
![photo_2021-08-12_11-31-47](https://user-images.githubusercontent.com/35047444/129215464-79de7796-97b9-4b95-8ebb-2312b92e40a7.jpg)
Ca**te de agulha

**Comment by matheusrazor** [comment]
![image](https://user-images.githubusercontent.com/53947083/129402173-07c01f07-fd42-4d1e-aa7f-88b1582163c7.png)

Virando jacaré
