### ISSUE TITLE
5 Curiosidade sobre você

### ISSUE THREAD

**Issue by RochaCarla** [fga-eps-mds/Qualifying-Software-Engineers-Undergraduates-in-DevOps#15]
Comente essa issue com 5 curiosidades sobre você =)

**Comment by RochaCarla** [comment]
1. Já fiquei na mesma mesa de bar durante toda a noite com o Brad Pitt
2. Já fiz a sonoplastia de uma peça de teatro e ganhamos o prêmio de melhor sonoplastia do "premio sesc do teatro candango"
3. Já fiz o caminho de Santiago de Compostela
4. Sempre acham que minha sobrinha é minha filha (somos muito parecidas)
5. Amo ir a shows/festivais de música (Devo ter ido em mais de 100 shows)

**Comment by Matheuspleal** [comment]
1. Já comi uma pimenta jalapeño inteira
2. Minha maior paixão (Fora a minha namorada hahaha) são games
3. Curto demais ver anime
4. Meu apelido é Mineiro mas sou de Brasília
5. Amo animais

**Comment by fellipepcs** [comment]
1- Adoro esportes.
2- Sou estagiário mais trabalho como Júnior
3- Adoro tocar contrabaixo e violão
4- Sou apaixonado por programação
5- Já fui jogador da base profissional de futebol

**Comment by AdneMoretti** [comment]
1. Adoro esportes, principalmente vôlei, futebol e musculação.
2. Tenho minha parte artística, já fiz teatro e curso básico de música (sei tocar um pouco de violino)
3. Amo tomar banho de mangueira e piscina
4. Gosto de banana pura, mas odeio qualquer comida com banana
5. Minha série favorita é Modern Family.

**Comment by PedroSiq** [comment]
1. Eu sou bem extrovertido e de fácil entrosamento;
2. Amo jogar videogames, principalmente jogos on-line como FPS. 
3. Também amo esportes;
4. Quem não conhece acha que minha mãe é minha irmã, porque ela me teve nova.
5. Nasci e cresci no interior de Goiás, antes de vir pra Brasília

**Comment by guigudf** [comment]
1. Adoro animes, mangas e video games
2. Viciado em impressão 3D 
3. Tenho uma estante cheia de figures
4. Faço a maioria das minha figures, seja por impressão ou papercraft
5. Amo esportes que não sejam futebol

**Comment by matheusmsvieira** [comment]
1. Sou casado e tenho uma filha de 6 meses
2. Sou bombeiro militar
3. Gosto muito de esportes e baralho
4. Amo cozinhar
5. Gosto de tocar violão e cantar

**Comment by Elios630** [comment]
1. gosto de animes
2. introvertido
3. gosto de vídeo games
4. tenho um cachorro
5. Nasci em Brasília

**Comment by hgaldino05** [comment]
1. Gosto muito de ler, principalmente durante a noite.
2. Sou Flamenguista. Torço também para o Southampton, time do sul da Inglaterra que disputa a Premier League.
3. Desde pequeno sou apaixonado pela franquia Pokémon, principalmente pelos games.
4. No meu tempo livre costumo assistir alguma coisa ou jogar no meu PC.
5.  Sou muito fã de animes/mangás. O meu favorito é Fullmetal Alchemist (tem o anime na Netflix :D )

**Comment by mc-gomes** [comment]
1. gosto muito de jogar/assistir futebol
2. tenho vontade de saltar de paraquedas um dia kk
3. quando eu mando áudio é quase sempre de no minimo 20seg, mas acho que em média são de uns 45seg
4. toco um pouco de violão e guitarra
5. demorei um tempinho pra pensar em 5 curiosidades sobre mim

**Comment by gabrielm2q** [comment]
1. já morei em 5 cidades diferentes
2. gosto de assistir esportes no tempo vago
3. gosto de ler (principalmente sobre astronomia)
4. gosto de animais (especialmente cachorros)
5. já tive algumas aulas de violão, mas não lembro de nada

**Comment by Thiab394** [comment]
1. Gosto muito de jogar, principalmente  jogos single player, jogo desde criança
2. Amo a cultura japonesa como um todo e seu idioma
3. já cursei 1 semestre de japonês por hobby e pretendo continuar
4. Gosto e tomo bastante água com gás
5. Tenho 3 gatos

**Comment by Eruel6** [comment]
1. Gosto muito de artes marciais, comecei a praticar tarde mas atualmente pratico duas.
2. Amo jogar tanto online quanto offline.
3. Tenho interesse em aprender alemão em algum momento da minha vida.
4. Gosto muito de História.
5. Gosto de qualquer tipo de jogo de baralho e board games.

**Comment by Madu01** [comment]
1. Sou chocolatra controlada (mas se me oferecer um bombom eu aceito)
2. faço hidroginástica 
3. já participei de corridas, uma delas foi a corrida de reis-DF fiz 6km na chuva sem parar 
4. quando eu tinha 4 a 5 anos cuidava de insetos como se fossem meus bebês, hoje em dia tenho pavor de insetos a um nível que eu acho semelhante a de fobia
5. sou apaixonada por gatos e lontras

**Comment by ticu-stack** [comment]
1. Falo 4 línguas;
2. já tive uma aranha de estimação que se chamava Rebeca (F Rebeca);
3. Poderia me alimentar só de pipoca pelo resto da vida;
4. Tenho irmãos trigêmeos;
5. Queria fazer mais amigos na universidade;

**Comment by GabriellyAssuncao** [comment]
1. Sempre quis ser programadora.
2. Apesar de gostar de ambos, eu prefiro jogos de tabuleiro a eletrônicos. Meu favorito é xadrez.
3. Curto muito a natureza e adoro fazer trilhas de bike.
4. Minha comida favorita é pizza.
5. As vezes eu desmarco rolês pra ficar assistindo série.

**Comment by laurapinos** [comment]
1- Já quebrei a clavícula porque tropecei
2- Amo ir no mercado
3- Sou muito prestativa
4- Amo todo tipo de atividade física
5- Já assisti todos os episódios de A Grande Família

**Comment by oCaioOliveira** [comment]
1- Uma vez cantei Galopeeeeeeeira por uns 30 segundos pra um ginásio cheio de gente e infelizmente gravaram :)
2- Sou um cinéfilo.
3- Viagem abre um sorriso na minha cara.
4- As vezes ronco igual uma máquina de cortar madeira.
5- Tenho uma melancia em forma de gato, vulgo "Rubi".
![WhatsApp Image 2022-01-26 at 00 28 52](https://user-images.githubusercontent.com/54439337/151099353-6f9d0b27-9f5a-41ef-92d8-d2f8cd205602.jpeg)

**Comment by lucasqueiroz23** [comment]
1 - Amo leitura!
2 - Luto boxe. Também sou louco com basquete e futebol.
3 - Quando era adolescente, eu rimava. Às vezes eu ficava horas no dia só fazendo isso. Cogitei participar de batalhas de rima, mas por algum motivo eu desisti. Acabei perdendo o jeito.
4 - Sou apaixonado por matemática. Se não cursasse ESW, não tenho dúvida de que estaria cursando matemática :)
5 - Sou muito prolixo. Escrever apenas 5 coisas foi difícil kkkkkkkkkkkk.

**Comment by beatrizSO** [comment]
1. já mudei de foco profissional 3 vezes, mas acredito que agora me encontrei com a agilidade;
2. já tive que fazer fisioterapia 3 vezes, sou uma jovem senhora;
3. amo muay thai e pilates, mas não pratico desde o começo da pandemia
4. amo serie/filme de zombie, se eu acreditasse em apocalipse zumbie com certeza teria um plano bem detalhado traçado kkkkk
5. sou de exatas mas amo biológicas e quase prestei vestibular pra isso

**Comment by laisramos123** [comment]
1. Adoro todo tipo de atividade física.
2. Uma das coisas que mais gosto é fazer os outros rirem. 
3. Sou um para-raio para rolês aleatórios e risca-faca.
4. Amo minha família e meus amigos, tenho 5 irmãos de pai e mãe.
5. Decidi que vou perseguir meus sonhos, custe o que custar.

**Comment by guibrbs** [comment]
1. Sou apaixonado em desenvolvimento web, especialmente em frontend e em ReactJs.
2. Tenho curso técnico em informática.
3. Gosto de jogar games, especialmente FPS.
4. Gosto de jogar e assistir basquete e futebol, torço pro Warriors e Vaxxxcão (Meteu essa?).
5. Curto muito praticar calistenia.

**Comment by HianPraxedes** [comment]
1. Gosto de jogar, mas ultimamente só tenho jogado LoL.
2. Gosto de vários esportes, mas meu favorito é vôlei.
3. Eu desenho no meu tempo livre.
4. Gosto de animes. Meu favorito é One piece.
5. Eu faço tudo o que estiver ao meu alcance para ver quem é importante pra mim feliz.

**Comment by MorettiGS** [comment]
1. Já dancei com uma fantasia de robô em um daqueles vídeos do "Harlem Shake".
2. Não gosto de comer qualquer fruto do mar.
3. Adoro qualquer tipo de jogo, pode ser cartas, tabuleiro, de computador, esportes, qualquer um!
4. Amo animais, inclusive já tive 5 cachorros ao mesmo tempo.
5. Gosto muito de doces.

**Comment by lucascard** [comment]
1. Já passei um mês trocando a noite pelo dia.
2. Sou viciado em rodízio de sushi
3. Trabalho com qualidade de software
4. Passo mal só de sentir o cheiro de suco de pêssego
5. Quebrei o rádio(osso do braço) depois de literalmente pisar na bola, jogando futebol.

**Comment by liander-alves** [comment]
1. Tenho atualmente 8 gatos e 1 cachorro.
2. Eu e minha namorada catalogamos e rankeamos a maioria dos restaurantes japoneses de Brasília.
3. Em algum momento de 2021 eu conseguia resolver cubos mágicos em menos de 1 min.
4. Na época de escola eu já fui o 19° melhor jogador do mundo com um personagem específico do LoL.
5. Sou um infiltrado de aeroespacial e minha meta é desenvolver sistemas operacionais pra foguetes.

**Comment by Mateusvff** [comment]
1. Meus hobbies preferidos são musculação e andar de kart
2. Já viajei pra 3 países diferentes
3. O melhor rolê pra mim é ir ao cinema
4. Já quis ser médico, nutricionista e confeiteiro KKKK
5. Nunca quebrei nenhum osso do corpo

**Comment by thiago-vivan** [comment]
1 - Já morei em 5 cidades diferentes
2 - Comecei a morar sozinho com 15 anos
3 - Já desci do topo de uma montanha sozinho, com 15 anos também, sem nunca ter andado de ski (quase chorei quando cheguei vivo)
4 - Curto demais filosofia e sociologia, por isso eu quase fui fazer psicologia
5 - quando eu fiz ENEM eu tinha nota pra passar em qualquer curso no brasil mas n sabia o que queria fazer, por isso acabei no gama podendo escolher depois kkk (deu tudo certo, to amando software!!!)

**Comment by iagocabral** [comment]
1. Ja voei em um caiaque preso em um parapente 
2. Desci a rampa do congresso nacional de skate 
3. ja passei a mão em um tubarão( em um oceanario hehe)
4. Viajei o nordeste inteiro de carro 
5. Tenho um cachorrinho lindo chamado Hayato

**Comment by charles-serafim** [comment]
1. Amo artesanato (meu último hobbie/vício foi o bookbinding e faço serigrafia)
2. Fui medalhista da OBMEP mas hoje em dia matemática da faculdade me deixa ansioso
3. Tenho 6 pés de pimenta em casa (e várias mudinhas que planto pra dar pras pessoas)
4. Já morei em 14 casas diferentes
5. Assisto reality shows de gosto duvidoso

**Comment by ahbreu** [comment]
1. Já morei fora do país e durante uma trilha cai no mar qd estava 0°C
2. Sou professor de inglês
3. Gosto muito de jogar, porém sou ruim em todos
4. Meu anime favorito é Shokugeki no Soma
5. Uso modulador de voz (e nome de menina) nos jogos pra ganhar skin

**Comment by MatheusHenrickSantos** [comment]
1. Tenho um irmão gêmeo que também estuda na UnB;
2. Gosto muito de astronomia. Tive a oportunidade de ver o cometa Leonard ano passado pelo meu telescópio;
3. Meu recorde no cubo mágico 3x3x3 é de 29 segundos. Sei montar também o cubo 2x2x2 e o 4x4x4.
4. Gosto de animes (cavaleiros de zodíaco, principalmente) e da cultura japonesa em geral. Estudo japonês para um dia poder conhecer o Japão. Já até sei comer usando hashis.
5. Certa vez eu quase morri sendo puxado por uma cachoeira.

**Comment by CorreiaJV** [comment]
1. Já joguei nas categorias de base do Brasília Vôlei e ficamos em segundo em um campeonato nacional de grande expressividade 
2. Gosto muito de gamificação, conheci na empresa Jr do curso e hoje estagio na área de desenvolvimento de uma Startup focada nisso(Movve)
3. Já morei em Uberlândia
4. Sou viciado em filmes e séries 
5. Gosto de assistir todos os esportes

**Comment by phnog** [comment]
1. Decidi fazer Software por causa de um filme.
2. Minha serie favorita e How I Met Your Mother.
3. As únicas coisas que eu faço e jogar e dormir. 
4. Já capotei de kart. 
5. Já joguei basquete e vôlei.

**Comment by MtsSrs** [comment]
1. Já tirei 1 mês da minha vida para zerar todos os Need for Speed e todos os Forzas (Falhei nos Forzas);
2. Pulei 2 anos de curso de inglês apenas com que aprendi em jogos online;
3. Já passei 4 horas dentro da academia só de lero lero mesmo....
4. Uma senhora desconhecida já me falou, no ônibus, que eu estava com cara de acabado (fim do semestre);
5. Na minha primeira semana de carteira de motorista bati no carro da Detran;

**Comment by vitormanoel17** [comment]
1 - Amo esportes, principalmente futebol
2 - Já caí em um poço
3 - Gosto de jogar jogos FPS, mesmo eu sendo horrível
4 - Ganhei 2 provas de atletismo (3 km e 800m) no JIF (Jogos dos Institutos Federais)
5 - Tenho praticado violão e calistenia nas horas vagas

**Comment by MatheusPerillo** [comment]
1. Aprendi tocar meu primeiro instrumento (violão) com 4 anos, mas hoje sou baterista
2. Sou autodidata na maioria dos instrumentos que toco hoje
3. Fiz uma cirurgia aos 8 meses de idade, porque nasci com uma condição rara chamada pé torto congênito.
4. Já fui chamado 4 vezes pra jogar futebol nos EUA, mas meus pais não deixaram por causa da curiosidade acima.. Tolinhos, poderiam estar milionários hoje KKKKK brinks
5. Amo nadar. Se você me chamar pra sua casa e tiver piscina eu vou entrar

**Comment by MateusCaltabiano** [comment]
1. Gosto muito de dirigir (Bom demais pra virar uber depois que me formar)
2. Toco violão e guitarra, já participei de uma banda no ensino médio
3. Adoro jogar videogame
4. Flamenguista desde que nasci
5. Já fiquei preso em um metrô na Alemanha

**Comment by murilopbs** [comment]
1 - Já engessei meus dois braços e minhas duas pernas
2 - Mesmo morando em Brasília desde que nasci, só passei uma vez o natal aqui
3 - Assisti à todos os jogos do Botafogo em 2020 e 2021
4 - Tô há quase 2 anos na autoescola e espero tirar a carteira no final de fevereiro
5 - Já fui campeão de um torneio de futevôlei

**Comment by EuricoAbreu** [comment]
1. Gosto de videogames
2. Já tentei aprender a tocar algum instrumento mas nunca deu certo
3. Além dos e-sports o único esporte que assisto é Formula 1
4. Leio HQs
5. Nasci e moro no Goiás

**Comment by LuizPettengill** [comment]
1.Não gosto de bebida alcoolica
2.Amo cachorros a ponto de estudar muito sobre como adestra-los
3.Vivo basicamente de cereal pq sou preguiçoso
4.Faço parte de uma familia gamer (jogo com frequencia c meus irmaos)
5.Gastei 200 reais em cerveja do harry potter na disney em um dia

**Comment by Julio-eng** [comment]
1. Gosto de series no formato sitcom.
2. Gosto de todos os tipo de arte, mas n sou bom em nenhuma 
3. Nas horas vagas - ou não tão vagas assim - gosto de jogar com os amigos.
4. Cursei um ano de engenharia civil antes de mudar para software.
5. Sou de Goianésia (GO) e vim para Brasília para estudar.

**Comment by EduardaSMarques** [comment]
1. Sou apaixonada em patinação no gelo, vôlei e tênis de mesa.
2. Faço aniversário no mesmo dia que minha irmã porém somos de anos diferentes e minha mãe não planejou as duas ser do mesmo dia.
3. Gosto de procurar músicas de idiomas diferentes 
4. Sou apaixonada em zoologia e astrologia 
5. Desde o 8° sou chamada de lêmure, até mesmo meus professores me chamavam  na época
