### ISSUE TITLE
Semana 0 - Fazendo uma receita de OVO

### ISSUE THREAD

**Issue by RochaCarla** [fga-eps-mds/Qualifying-Software-Engineers-Undergraduates-in-DevOps#3]
# Descrição

Iniciando as atividades do semestre, começaremos com um experimento bem simples. O que podemos fazer usando Ovo como ingrediente principal? Usem sua criatividade para fazer uma receita de OVO e compartilhe com a turma

# Tarefas
Para completar esse desafio devemos
- [ ] Fazer uma receita que o OVO é o ingrediente principal (usem a criatividade.. ovo frito, ovo cozido, etc)
- [ ] Tirar foto dessa receita (uma self da receita com seu rosto é um plus pra gente se conhecer nesse mundo virtual)
- [ ] Postar a foto aqui nos comentários dessa issue com o nome da receita (pode até ser uma receita inventada) e descreva o gosto da sua receita :)

# Critério de aceitação

- [ ] A sua tarefa está finalizada quando postar aqui até o dia 22/07

**Comment by RochaCarla** [comment]
Exemplo de receita - ovo balut
receita tipica da filipina.. Nunca comi e espero nunca experimentar :) dizem que o gosto é bastante acentuado e a textura bem única (ossos e penas, misturados a textura de ovo) - nao recomendo :(

![balut_egg](https://user-images.githubusercontent.com/5897389/126353273-800614f0-75f7-4435-b4d5-73dd28f77097.jpg)

**Comment by PedroCassianoMartins** [comment]
![20210720_122358](https://user-images.githubusercontent.com/87657942/126375353-9f5b23bd-182c-455b-a92c-f7388ee74b56.jpg)
2 ovos fritos no almoço, ótimo para substituir a proteina da carne quando não tem. Comum aqui em casa por ser gostoso e dar um sabor a mais no comum arroz e feijao

**Comment by Ericklevy** [comment]
![image](https://user-images.githubusercontent.com/48847770/126402688-00a016be-1a0a-4283-aaf0-4f89c39c0455.png)
ovos mexidos com tempero

**Comment by ggomesbr** [comment]
![IMG_20210721_112448](https://user-images.githubusercontent.com/78509975/126526492-2d388907-2e94-4827-8cdd-c4ebf9d06957.jpg)
Ovo frito com queijo 😜✌🏿

**Comment by AmandaNbr** [comment]
![WhatsApp Image 2021-07-21 at 16 42 32](https://user-images.githubusercontent.com/44625056/126550888-f4faaab3-0378-41cb-aea8-a550abe3a500.jpeg)

Esse é um tamagoyaki, que é basicamente uma omelete em formato de rocambole. A forma de fazer é muito interessante! É necessário uma panela antiaderente, então derrete-se a manteiga e um pouco do ovo batido até ele ficar sequinho, após isso é preciso enrolar o ovo, deixá-lo em um canto da panela, adicionar manteiga e mais um pouco do ovo batido e assim repetidamente, no final fica esse rolinho super saboroso! Eu ainda coloquei umas pétalas de uma planta que tem aqui em casa pra ficar mais chique, não sei se deu certo.

**Comment by victorear05** [comment]
Crepeoca com bacon e calabresa  
A crepeoca é feita com ovos e polvilho, daí decidi adicionar bacon e calabresa pra ficar melhor ainda!  
![20210721_192653.jpg](https://user-images.githubusercontent.com/78758172/126568105-ed004b8d-aab1-4f36-9697-45601da00c21.jpg)

**Comment by pedrohelias** [comment]
![20210721_201705](https://user-images.githubusercontent.com/30875663/126571755-084b4e01-2f07-403c-a2fd-adf1b3151e9c.jpg)

Eu e essa grandíssima receita chamada Shakshuka(misturado, sacudido), também conhecido como "Ovos no Purgatório" (covenhamos que esse nome é bem mais chocante e representa bem melhor o resultado final hahaha). É considerada um prato Argelino, embora tenha sido popularizado em Israel. Basicamente, são ovos cozidos dentro de um molho de tomate bastante temperado. Opto por comer com pão porque fica sensacional. O sabor é absurdo e fãs de tomate vão curtir bastante!

**Comment by matheusrazor** [comment]
![WhatsApp Image 2021-07-21 at 20 33 02](https://user-images.githubusercontent.com/53947083/126572726-515a7cd8-d470-492a-8256-71a206c856e4.jpeg)

Prato principal: Ovos cozidos. Acompanhamento: Miojo de costela picante

**Comment by victordscabral** [comment]
![20210721_213306](https://user-images.githubusercontent.com/87657291/126576241-21b1a0d8-1d06-42a8-a961-09777d9c657e.jpg)

Famoso omelete pra comer de jantar. Ele tava meio triste porque não é muito fã do frio que tava de noite, então resolvi deixar ele mais feliz 😁.

**Comment by LamequeFernandes** [comment]
![photo_2021-07-21_22-37-41](https://user-images.githubusercontent.com/79016306/126579479-791c3ca7-f725-4200-a37b-a920309df392.jpg)
Meu amado cuscuz com queijo e ovos :D

**Comment by jvsdurso** [comment]
https://user-images.githubusercontent.com/69814362/126580613-743cd7bc-aeab-45de-985b-a478ef5e73d5.mp4

Meu ovo poché :) ! Estava pensando em fazer algo mais elaborado, mas aqui onde estou não tem muitos equipamentos culinários...


Ingredientes: 
1 Ovo
q/b Sal
q/b Pimenta
q/b Páprica doce (ou picante)

Coloque o ovo em um pedaço de plástico filme e enrole as pontas, fechando bem, formando uma "trouxinha". Ponha as "trouxinhas" na água fervente e cozinhe por 6 minutos (gema mole) a 8 (bem passado). Para servir, retire do plástico. 

Obs.: Ovo poché é melhor com a gema mole :P

**Comment by klyssmannoliveira** [comment]
![IMG_20210721_221932](https://user-images.githubusercontent.com/56873266/126588580-ad5bc620-7e47-4998-922d-a59fc6f4eb3c.jpg)

Não podia faltar o tradicional pão com ovo. É uma receita muito simples de ser feita, basta comprar um pão na padaria mais próxima e fritar o ovo na frigideira (com óleo ou manteiga, dependendo do seu orçamento). E, aqui entre nós, quando a grana tá curta esse pão com ovo salva o lanche. Bom semestre a todos!

**Comment by PedroLSF** [comment]
![rECEITA](https://user-images.githubusercontent.com/85000470/126633650-ff75b010-b7e5-4547-ac61-491c3a253c13.jpg)
Ovo cozido com um pãozinho ;D

**Comment by EduardoGurgel** [comment]
![1](https://user-images.githubusercontent.com/51385738/126636422-e49d83f3-dd6b-4f26-9e74-2d10f090cd56.jpeg)
Meu café da manhã de todos os dias. Ovo com cuscuz, muito booom.

**Comment by Pedro-V8** [comment]
Aquele omelete básico matinal, é o que temos pra hoje.
![omelete](https://user-images.githubusercontent.com/71507198/126636669-1f32f720-f376-469c-ad99-e04d5e8bd84c.jpg)

**Comment by AnaCarolinaRodriguesLeite** [comment]
Sanduíche de ovo (sal e orégano), presunto, queijo e ricota.
![WhatsApp Image 2021-07-22 at 09 13 34](https://user-images.githubusercontent.com/49570180/126638130-c74bfa4d-f5c3-46a3-8937-6bc2c0adc440.jpeg)

**Comment by gatotabaco** [comment]
Dois ovos batidos, sal, tomate, manjericão fresco, orégano, 4 fatias de mussarella de Búfala picadas, 2 fatias de peito de Peru picadas. Misturar e fritar na manteiga, com um pouco de cebola cortada bem fina e picada.
![ee1fe7df-740a-4e69-9efb-ae53619a2b14](https://user-images.githubusercontent.com/54778783/126641352-05bb476d-dd07-4a13-8f14-c936c68a0824.jpg)

**Comment by Thais-ra** [comment]
Famoso pão com ovo
![photo_2021-07-22_09-55-38](https://user-images.githubusercontent.com/35047444/126642409-f7d860b7-a71d-47f8-b0b7-b9db064bbb01.jpg)

**Comment by augustocrmg** [comment]
![98e01a46-cd0b-44c4-a42f-45ead9b3734f](https://user-images.githubusercontent.com/58157221/126643053-143be2af-8834-4c7f-9732-515fbd445080.jpeg)
Crepioca 
1 Ovo 
2 Colheres de goma de tapioca 
1 Pitada de sal
1 Colher de queijo provolone,
por fim um pouco de orégano.
Fica muito bom de manhã pois é uma receita com um gosto bem leve.

**Comment by Alladin-51** [comment]
> # Descrição
> Iniciando as atividades do semestre, começaremos com um experimento bem simples. O que podemos fazer usando Ovo como ingrediente principal? Usem sua criatividade para fazer uma receita de OVO e compartilhe com a turma
> 
> # Tarefas
> Para completar esse desafio devemos
> 
> * [ ]  Fazer uma receita que o OVO é o ingrediente principal (usem a criatividade.. ovo frito, ovo cozido, etc)
> * [ ]  Tirar foto dessa receita (uma self da receita com seu rosto é um plus pra gente se conhecer nesse mundo virtual)
> * [ ]  Postar a foto aqui nos comentários dessa issue com o nome da receita (pode até ser uma receita inventada) e descreva o gosto da sua receita :)
> 
> # Critério de aceitação
> * [ ]  A sua tarefa está finalizada quando postar aqui até o dia 22/07

![Uploading Screenshot_2021-07-22-09-49-31-826_com.whatsapp.jpg…]()

**Comment by Alladin-51** [comment]
Ovo mexido

**Comment by thiago-vivan** [comment]
![image](https://user-images.githubusercontent.com/80918128/126644736-3b47a061-0493-4614-8e8c-9a775bef1093.png)

ovo frito com queijo, torrada e calabresa

**Comment by LuizPettengill** [comment]
![16269598134537126800122614686135](https://user-images.githubusercontent.com/44177946/126645239-51741c0a-a399-41e5-9a9a-65481d024f39.jpg)
Faz um furo no pão frita o ovo no meio

**Comment by SwampTG** [comment]
Tentativa de Shakshuka. Dois ovos,  tomate, cebola, pimentão, alho, cominho, pimenta do reino e cheiro-verde. Acompanhado por torradas.

**Comment by Eduardo-RFarias** [comment]
![WhatsApp Image 2021-07-22 at 10 20 19 AM](https://user-images.githubusercontent.com/52677538/126645729-2844d15c-a0dd-4d00-ae04-ed8ebcf42039.jpeg)


O famoso, o clássico, o mais amado pão com ovo !!!

Um prato pomposo, gostoso e simples, é tão fácil que eu fiz 10 minutos antes de começar a aula :O

Tudo que você precisará é:

- Pão velho
- Ovo
- Manteiga

Frite o pão, o ovo (com a gema mole) junte os dois e pufff, você tem o prato feito.
Combina com qualquer acompanhamento.
Estusiosos da FAFIFO (Faculdade de Filosofia de Formosa) afirmam que o sabor é realçado em 40% quando a receita é feita com pão dormido.

Prós: 

- É gostoso
- É simples
- Aproveita aquele pão velho que você deixaria mofar

Contras:

- Você não vai querer comer só um (e normalmente n tem muito pão velho sobrando :v)
- Só isso :D

**Comment by matheusakio** [comment]
![image](https://user-images.githubusercontent.com/73257118/126713354-44bfaad8-023d-440a-814e-0baa687452fc.png)
Farofa de ovo, muito simples e gostoso.

**Comment by RochaCarla** [comment]
![image](https://user-images.githubusercontent.com/5897389/126993029-9819df91-746d-4b45-a426-a4ce9fff34e1.png)
