### ISSUE TITLE
Temas dos projetos 2022-1

### ISSUE THREAD

**Issue by RochaCarla** [fga-eps-mds/Qualifying-Software-Engineers-Undergraduates-in-DevOps#43]
# Descrição

Cada grupo deve comentar a issue com as seguintes informações

- [ ] Nome do grupo
- [ ] Link do repositorio git
- [ ] Resumo do problema  que vcs vao trabablhar
- [ ] Um rascunho do escopo do software
- [ ] Contato (gitname) do scrum master

**Comment by yagompassos** [comment]
Grupo 5 - Óia a Moeda

https://github.com/fga-eps-mds/2022-1-Squad5

Grande flutuação nos preços das cryptos e dificuldade de acompanhar os preços e noticias das moedas. Descentralização das informações sobre o assunto.

Os épicos vão ser: contas de usuários e relatórios. O software vai permitir que o cliente acesse a plataforma, pesquise preços e informações sobre as moedas e ações que ele quiser. Caso seja da sua vontade, esse cliente pode criar uma conta para salvar suas preferências e acessar as informações atualizadas com maior facilidade e agilidade.

SM Fixo- https://github.com/Eruel6
SM da Sprint - https://github.com/yagompassos

**Comment by Luckx98** [comment]
# Nome do Grupo
AvaliaUnb

## Link repositório 
https://github.com/fga-eps-mds/2022-1-Squad2

## Resumo 
Projeto com o objetivo de ajudar alunos com relação a disciplinas e professores. O estudante ao realizar a matéria, avaliaria a disciplina com níveis de dificuldade (entre 0 a 5), compartilhando sua experiência de como foi e o que recomendaria para as próximas pessoas a fazê-la, como exemplo livros a serem estudados, didática do professor, desafios principais da matéria, entre outras coisas. Alem disso, será possível exercer uma interação no software 

 ## Escopo
O software terá um sistema de criação de conta dos estudantes, com isso, vai ter acesso ao Dashboard das matérias e poderá realizar a comunicação com outros membros para pedir dicas ou ajuda.

## SM Fixo
Lucas Macedo https://github.com/Luckx98
## SM da sprint
Lucas Gabriel https://github.com/lucasgabriel-2

**Comment by leommiranda** [comment]
- Nome do grupo: TiControla
- Link do repositorio git: [TiControla](https://github.com/fga-eps-mds/2022-1-TiControla)
- Resumo do problema que vcs vao trabalhar: controle de gastos
- Um rascunho do escopo do software: Um aplicativo onde a pessoa entre com um login e consiga ver suas entradas e saídas do mês, consiga consultar outros meses e talvez também ter um controle dos gastos no cartão de crédito. Estamos analisando a viabilidade de escanear os extratos de algum banco para preencher parte das informações automaticamente ("receipt scanning").
- Contato (gitname) do scrum master: @leommiranda e @milenaaires
- Contato (gitname) do product owner: @maltaliz

**Comment by luciano-freitas-melo** [comment]
- **Nome do grupo:** GFour
- **Link do repositório git:** [GFour-Invext](https://github.com/fga-eps-mds/GFour-Invext)
- **Resumo do problema que vocês vão trabalhar:** Alto número de investidores entrando no mercado e poucos softwares gratuitos e funcionais para auxiliar o usuário a acompanhar sua carteira de investimentos
- **Rascunho do escopo do software:** Uma aplicação web em que o usuário possa realizar um login e ter acesso ao um dashboard, podendo inserir seus ativos e acompanhá-los em tempo real na bolsa de valores através de gráficos e dados relevantes sobre a sua carteira de investimentos
- **Scrum Master:** [luciano-freitas-melo](https://github.com/luciano-freitas-melo)
- **Product Owner:** [MariaAbritta](https://github.com/MariaAbritta)

**Comment by JoaoSchmitz** [comment]
### Nome do Grupo 3
PokéRanking

### Link do repositório
[Repositório - PokeRanking](https://github.com/fga-eps-mds/2022-1-PokeRanking)

### Resumo
Esse aplicativo tem como objetivo ajudar jogadores casuais dos jogos da série Pokémon a escolher entre as diferentes criaturas para formar suas equipes, pois a quantidade de pokémons diferentes é enorme, necessitando conhecimento prévio ou muito tempo para conhecer todos.

### Escopo
Um aplicativo para classificar e ordenar pokémons de acordo com os status destes nos jogos de videogame da série. Permitindo o usuário a filtrar, pesquisar e comparar pokémons de sua escolha, além de mostrar rankings relativos aos status.

### Scrum Masters
[João Matheus](https://github.com/JoaoSchmitz)
[Thiago Cerqueira Borges](https://github.com/Thiago-Cerq)

**Comment by hannanhunny01** [comment]
### Nome do grupo 6 
B-Tracker
### Link do respositorio
[B-tracker](https://github.com/fga-eps-mds/B-Tracker)
### Resumo
Bug Tracker  ou sistema de rastreamento de bugs é um aplicativo de software que acompanha os bugs de software relatados em projetos de desenvolvimento de software. Pode ser considerado como um tipo de sistema de rastreamento de problemas.
### Escopo 
Bug tracker é a solução perfeita para rastrear bugs ou issues de um  produto ou aplicativo. O sistema de rastreamento de bugs permite que um único ou um conjunto de desenvolvedores continuem a rastrear bugs não finalizados em seus produtos com sucesso.

**Scrum Master** [João Lucas Pinto Vas](https://github.com/HacKairos)
**Product Owner** [Matheus Henrick Dutra](https://github.com/MatheusHenrickSantos)
